language: node_js

branches:
  only:
    - master
    - dev

node_js:
  - 9.8.0

cache:
  yarn: true
  directories:
    - node_modules

before_install: 
  #cd to our project
  - cd serverus

install: 
  #install packages
  - yarn

script:
  - yarn build
  - yarn travis

