language: node_js

node_js:
  - 9.8.0

cache:
  directories:
    - node_modules

before_install: 
  - cd serverus

install: 
  - npm install

script:
  - npm run build
  
after_script:
  - npm test -a
