// Log In/Out
export const LOG_IN_LOADING = "LOG_IN_LOADING";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAILURE = "LOG_IN_FAILURE";
export const LOG_OUT = "LOG_OUT";

//User Creation
export const CREATE_ACCOUNT_LOADING = "CREATE_ACCOUNT_LOADING";
export const CREATE_ACCOUNT_SUCCESS = "CREATE_ACCOUNT_SUCCESS";
export const CREATE_ACCOUNT_FAILURE = "CREATE_ACCOUNT_FAILURE";

//Password Management
export const REQUEST_PASS_RESET = "REQUEST_FORGOT_PASSWORD";
export const REQUEST_PASS_SUCCESS = "REQUEST_PASS_SUCCESS";
export const REQUEST_PASS_FAILURE = "REQUEST_PASS_FAILURE";
export const CHANGE_PASS_LOADING = "CHANGE_PASS_LOADING";
export const CHANGE_PASS_SUCCESS = "CHANGE_PASS_SUCCESS";
export const CHANGE_PASS_FAILURE = "CHANGE_PASS_FAILURE";

//UI Help Indicators
export const DISPLAY_PASSWORD_HELP = "DISPLAY_PASSWORD_HELP";
export const REMEMBER_ME = "REMEMBER_ME";

//Clear
export const CLEAR_STATUS = "CLEAR_STATUS";
