// Log In/Out
export const LOG_IN_LOADING = "LOG_IN_LOADING";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_FAILURE = "LOG_IN_FAILURE";
export const LOG_OUT = "LOG_OUT";

//User Creation
export const CREATE_ACCOUNT_LOADING = "CREATE_ACCOUNT_LOADING";
export const CREATE_ACCOUNT_SUCCESS = "CREATE_ACCOUNT_SUCCESS";
export const CREATE_ACCOUNT_FAILURE = "CREATE_ACCOUNT_FAILURE";

//Password Management
export const REQUEST_FORGOT_PASSWORD = "REQUEST_FORGOT_PASSWORD";
export const DISPLAY_PASSWORD_HELP = "DISPLAY_PASSWORD_HELP";
